### ISSUE TITLE
Include support for SBOM signing using cosign

### ISSUE THREAD

**Issue by nwl** [anchore/sbom-action#153]
Once https://github.com/anchore/syft/issues/510 is merged, the SBOM action should be updated to include parameters to sign the SBOM and upload the image and/or attestation to a URL (eg GitHub Package Registry)

**Comment by developer-guy** [comment]
we (w/@dentrax) can work on this if nobody interested in it @wagoodman

**Comment by kzantow** [comment]
There doesn't seem to be a lot of need for this from the community, so I'm going to close this for now. We can always revisit if there is interest.
