### ISSUE TITLE
Uploading sbom spdx file to Github enterprise is failing.

### ISSUE THREAD

**Issue by abgargexpe** [anchore/sbom-action#175]
We are testing out sbom-action github actions in Github Enterprise version 3.2.6. sbom file is created but, while attaching spdx file to Release, it is failing with exception: 

Error uploading to https://media.<github url>/releases/1334/files: 404 

Looking into the issue, it seems media url is not supported in github api. 

Is this behaviour because of Github Enterprise server or some permission issues with GITHUB_TOKEN?

**Comment by kzantow** [comment]
@abgargexpe sorry for the delay getting back to this! Unfortunately, I don't have access to a GHE instance to try to diagnose what's going on. As I understand it, using `oktokit` should make this work out of the box. Are there any configuration options you might have provided that could influence octokit to use `https://media...`?
