### ISSUE TITLE
 sbom-action Windows support

### ISSUE THREAD

**Issue by jauderho** [anchore/sbom-action#181]
I was not sure if sbom-action had Windows support so I figured I'd give it a try. 

See https://github.com/jauderho/sandbox/actions/runs/1765197587

It looks like WSL does not have a distribution installed: https://github.com/jauderho/sandbox/runs/4990001370?check_suite_focus=true#step:8:1

**Comment by kzantow** [comment]
Hi @jauderho -- the docs note how to get Windows support working:

https://github.com/anchore/sbom-action#windows

**Comment by kzantow** [comment]
Please reopen this issue if this does not work for you!
