### ISSUE TITLE
SBOM badge & user-friendly view

### ISSUE THREAD

**Issue by kzantow** [anchore/sbom-action#2]
Provide a way to generate an SBOM badge that users can add to their Github repositories with a user-friendly view when clicked, like an HTML table output for example.

**Comment by luhring** [comment]
I think this is a _fantastic_ idea! I had been thinking about a simple website that "renders" SBOMs for folks in a digestible way (e.g. maybe with sorting, filtering, etc.). I don't want to block the "badge" concept on that idea's development, but it could be a nice central place to link to from badges at some point.
