### ISSUE TITLE
Request: new release of sbom-action?

### ISSUE THREAD

**Issue by zdtsw** [anchore/sbom-action#330]
Can we expect a new release to be published soon?
The current latest v0.11.0 is from April and a new commit to upgrade syft to 0.53.4 was done 8 days ago.

I have some issue to use sbom-action on WSL with the image just built from previous GH action step, so I would like to try out and see if it is from the old version of syft or something is really wrong.

Thanks! @kzantow

**Comment by kzantow** [comment]
Done -- [v0.12.0](https://github.com/anchore/sbom-action/releases/tag/v0.12.0) is released! And lease let me know if there are issues using WSL!

**Comment by zdtsw** [comment]
Thanks @kzantow 
Upgraded to the new version of action and got 0.53.4, I think the problem is indeed with WSL enabled on windows https://github.com/anchore/sbom-action/issues/334
