### ISSUE TITLE
Problem to generate sbom for windows image

### ISSUE THREAD

**Issue by zdtsw** [anchore/sbom-action#334]
Hi,
I am some problem to get sbom-action working on windows image.
By same workflow on Linux images everything goes well.
Here is what I've done sofar:
- followed the instruction https://github.com/anchore/sbom-action#windows to add "Vampire/setup-wsl" on a "windows-2022" runner.
- built the windows image named "eclipse-temurin:8u332-b09-jre-nanoserver-ltsc2022" with Dockerfile from source repo. 
- done "docker image ls", to confirm the image is successfully created by GH action
- ran  `anchore/sbom-action` got error:
`* failed to construct source from user input "eclipse-temurin:8u332-b09-jre-windowsservercore-ltsc2022": could not fetch image "eclipse-temurin:8u332-b09-jre-windowsservercore-ltsc2022": unable to use OciRegistry source: failed to get image from registry: no child with platform linux/amd64 in index eclipse-temurin:8u332-b09-jre-windowsservercore-ltsc2022`

Since I do not have a windows to reproduce it locally, my guess is, even it is on
````
Runner Image
  Image: windows-2022
  Version: 20220[8](https://github.com/zdtsw/containers/runs/7931213744?check_suite_focus=true#step:1:9)16.1
  Included Software: https://github.com/actions/runner-images/blob/win22/20220816.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20220816.1
```` 
After setting up WSL, syft consider this is a Linux OS, that's why it does not use the images built by previous step nor can pull down image with the same name from public registry to match "platform linux/amd64"

I am using the latest `sbom-action`, which has `v0.53.4 syft`

**Comment by kzantow** [comment]
Thanks for following up @zdtsw, I'll have to retest this specific scenario and see if there's a way to fix this or maybe specify the architecture.

**Comment by kzantow** [comment]
Hi -- it looks like this has been fixed for a while, since we stopped requiring running on WSL. Note this particular image needs a platform if not using a windows runner, but using `windows-latest` works well to find a `windows/amd64` image: https://github.com/kzantow-anchore/sbom-action-test/actions/runs/9993969901/job/27622651136#step:4:248 -- please let us know if you have any more problems!
