### ISSUE TITLE
Using `artifact-name` breaks uploading artefact

### ISSUE THREAD

**Issue by ajmalab** [anchore/sbom-action#395]
Hi, 

Using the `artifact-name` option to upload the sbom with a custom name makes the upload-artfact action fail with a `ENOENT: no such file or directory` error.

**Comment by kzantow** [comment]
Hi @ajmalab could you provide the YAML configuration you're using?

**Comment by ajmalab** [comment]
Hi, apologies, I figured out the issue. I was using ${{ github.repository }} in the name, and that outputs a forward slash. The upload part interprets that as a folder path rather than the string. Replacing the forward slash with another character solved this.

**Comment by kzantow** [comment]
Thanks for following up @ajmalab and thanks for using our tools!
