### ISSUE TITLE
Using `image:tag` for input results in invalid artifact names

### ISSUE THREAD

**Issue by coxauto-kennyg** [anchore/sbom-action#396]
Using `image:tag` for input results in invalid artifact names.

```
Error: Artifact name is not valid: `<redacted>-python:3.9.spdx.json`. Contains the following character:  Colon :
          
Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash /
          
These characters are not allowed in the artifact name due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential problems with downloads on different file systems.
```

**Comment by kzantow** [comment]
This seems to be a limitation with GitHub workflow artifacts, I'm not sure it's something we can change/fix. Did you have any suggestions?

**Comment by coxauto-kennyg** [comment]
I'd be satisfied with the default artifact name being used for images too.

**Comment by kzantow** [comment]
Is there a workflow action you could provide that reproduces this? Are you specifying the `artifact-name` with the `image:tag` format? If so, just use a different artifact name.

If the action is generating the name, it replaces all the special characters from the `image` value, including `:` with underscore (`_`).

E.g. if I specify `localbuild/testimage:latest`, the artifact name is: `localbuild-testimage_latest.spdx.json`

**Comment by coxauto-kennyg** [comment]
unfortunately, I'm unable to reproduce on public github. we have an artifactory acting as a proxy for docker hub as described here https://www.jfrog.com/confluence/display/JFROG/Docker+Registry. The image I was using `registry.domain.com/python:3.9` breaks things. I can workaround it by specifying the artifact-name. thanks for looking into this.
