### ISSUE TITLE
Uploading dependency snapshot is not working because of PURL containing backslash

### ISSUE THREAD

**Issue by KimBartikowski5337** [anchore/sbom-action#414]
**What happened**:
The step `Uploading workflow artifacts` resulted in an error.
The error message contains the following: 

```
Warning: Error uploading depdendency snapshot: {
[...]
"message": "invalid package url: in manifest \"[..].ecr.eu-central-1.amazonaws.com/akhq:latest:/bin/busybox\" decoding \"\": scheme is missing",
[..]
}
```

**What you expected to happen**:
Upload of the dependency snapshot is successful. 

**Steps to reproduce the issue**:

- Use an container image as input to be scanned which contains busybox as a library e.g. alpine as base image

**Environment**:
- syft version: 0.76.0

Do you have any idea whether this is a misconfiguration or is this maybe a bug?

**Comment by mortenhauberg** [comment]
I've tried with

* `node:lts-alpine3.17`
* `php:8.2-alpine3.16`
* `golang:alpine3.17`
* `python:alpine3.17`
* `alpine:latest`

Looks like it's any `alpine` images.

Please let me know if there's anything else I can do to help

**Comment by kzantow** [comment]
Hi all -- I've had a bit of a look at this and from what I can tell, the only thing Syft is doing (for example with `alpine:latest`) is encoding the ampersand (`&`) in the purl to `\u0026`. I believe this is valid JSON and I'm a little confused why this is failing to be processed by GitHub, maybe it's an issue on their end?

As a workaround, I've made a change to the GitHub exporter that hopefully solves the problem for you: https://github.com/anchore/syft/pull/1782

**Comment by kzantow** [comment]
Hi @KimBartikowski5337 @mortenhauberg -- would you be able to try `v0.14.2`? I've updated Syft to _not_ escape HTML characters for the GitHub output, which I _think_ should fix this problem for you. From what I could tell, the only backslashes were due to escaping HTML characters to JSON escape sequences. The update to Syft v0.80.0 adjusts this behavior so this escaping does not happen. As far as I could tell, this is a GitHub issue if it cannot accept escaped sequences in JSON, but it would be great to verify this change in behavior fixes things for you!

**Comment by mortenhauberg** [comment]
```yaml
      - name: Generate SBOM
        uses: anchore/sbom-action@v0.14.2
        with:
          image: 'php:8.2-alpine3.17'
          output-file: sbom.spdx.json
          dependency-snapshot: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          artifact-name: sbom.spdx.json
          format: spdx-json
```

is giving me

```
------------------------- Uploading workflow artifacts -------------------------
/tmp/sbom-action-hLK3US/sbom.spdx.json
Uploading GitHub dependency snapshot from /tmp/sbom-action-hLK3US/github.sbom.json
Warning: Error uploading depdendency snapshot: {
  "url": "https://api.github.com/repos/**********/dependency-graph/snapshots",
  "status": 422,
  "headers": {
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
    "connection": "close",
    "content-length": "244",
    "content-security-policy": "default-src 'none'",
    "content-type": "application/json; charset=utf-8",
    "date": "Mon, 08 May 2023 05:24:03 GMT",
    "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
    "server": "GitHub.com",
    "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
    "vary": "Accept-Encoding, Accept, X-Requested-With",
    "x-content-type-options": "nosniff",
    "x-frame-options": "deny",
    "x-github-api-version-selected": "2022-11-28",
    "x-github-media-type": "github.v3; format=json",
    "x-github-request-id": "A00D:089D:43009A:8BC06B:64588773",
    "x-ratelimit-limit": "100",
    "x-ratelimit-remaining": "99",
    "x-ratelimit-reset": "1683523503",
    "x-ratelimit-resource": "dependency_snapshots",
    "x-ratelimit-used": "1",
    "x-xss-protection": "0"
  },
  "data": {
    "message": "invalid package url: in manifest \"php:8.2-alpine3.17:/bin/busybox\" decoding \"\": scheme is missing",
    "documentation_url": "https://docs.github.com/rest/reference/dependency-graph#create-a-snapshot-of-dependencies-for-a-repository"
  }
}
```

**Comment by JannickKemming1997** [comment]
Hi @kzantow, I've tested v0.14.2 on behalf of @KimBartikowski5337 since we're on the same team. Sadly, we're also getting the same result as Morten:
```
"message": "invalid package url: in manifest \"[...].ecr.eu-central-1.amazonaws.com/akhq:latest:/bin/busybox\" decoding \"\": scheme is missing"
```

**Comment by JannickKemming1997** [comment]
Can confirm it's working now, thank you very much! I suggest we close this issue.

**Comment by KimBartikowski5337** [comment]
As @LennardWesterveld wrote, using the more recent syft version (v0.92.0) fixed the problem.
