### ISSUE TITLE
Enhance specifying the mandatory "platform"  arg for multi arch images

### ISSUE THREAD

**Issue by saisatishkarra** [anchore/sbom-action#419]
Syft version after 0.75 fails to generate SBOM for multi-arch images and requires explicitly specifying the --platform option even when using the SHA specific to architecture.

Enhance specifying the  --platform option when scanning images as an input arg to the Syft arguments.

New Feature PR on Syft that is causing the problem: https://github.com/anchore/syft/pull/1801

How to reproduce:
```
Syft packages -v image:tag@sha256:<any-non-amd64-arch> -o spdx-json > sbom.spdx.json 
Error: * failed to construct source from user input image:tag could not fetch image: unable to use DockerDaemon source: image has unexpected architecture "arm64", which differs from the user-specified architecture "amd64
```

**Comment by willmurphyscode** [comment]
Thanks for opening this issue! The underlying issue in stereoscope has been fixed, see https://github.com/anchore/stereoscope/issues/188. Once we do a syft release that pulls in the stereoscope fix, probably early next week, this issue should be fixed as well.
