### ISSUE TITLE
sbom-action not working with docker-in-docker GitHub actions runner

### ISSUE THREAD

**Issue by apr-1985** [anchore/sbom-action#424]
I build a docker container using the `docker/setup-buildx-action@v2.6.0` and `docker/build-push-action@v4.1.0`  actions. But do not push the container to Artifactory at this point.

The image is built and loaded into docker fine, however when I try to run this action it cannot find the image locally and appears to be looking for a podman sock rather than docker.

```
- name: Generate SBOM
        id: sbom
        uses: anchore/sbom-action@v0
        with:
          image: "${{ inputs.registry }}/${{ inputs.image_name }}:${{ steps.image_date_tag.outputs.TAG_NAME }}"
```

gives the error (PII removed from container and repo names)

```
[0000] DEBUG no socket address was found. Trying default address: /run/user/1001/podman/podman.sock from-lib=stereoscope
  [0000] DEBUG looking for socket file: stat /run/user/1001/podman/podman.sock: no such file or directory from-lib=stereoscope
  
  [0000] DEBUG image: source=OciRegistry location=docker-local.my.artifactory.systems/gha-scaleset-runner:20230621-121746 from-lib=stereoscope
  
  [0000] DEBUG pulling image info directly from registry image="docker-local.my.artifactory.systems/gha-scaleset-runner:2023062-[121](https://github.com/my_org/my_repo/actions/runs/5333937405/jobs/9665073233#step:13:122)746" from-lib=stereoscope
  [0000] DEBUG no registry credentials configured, using the default keychain from-lib=stereoscope
  
  2023/06/21 12:22:03 error during command execution: 1 error occurred:
  	* failed to construct source from user input "docker-local.my.artifactory.systems/gha-scaleset-runner:20230621-121746": could not fetch image "docker-local.my.artifactory.systems/gha-scaleset-runner:20230621-121746": unable to use OciRegistry source: failed to get image descriptor from registry: GET https://docker-local.my.artifactory.systems/v2/gha-scaleset-runner/manifests/20230621-121746: MANIFEST_UNKNOWN: The named manifest is not known to the registry.; map[manifest:gha-scaleset-runner/20230621-121746/manifest.json]
```

I am not sure why it is looking for a podman socket when all the documentation refers to using docker and I cannot find a config option for this.

Thanks for the help.

**Comment by apr-1985** [comment]
This is a strange one as the Env var is definitely set as I can run Docker commands (e.g. docker images https://github.com/anchore/sbom-action/issues/424#issuecomment-1631548435)  in the Workflow and build my test container and push it to Artifactory.

Does the Syft Action run in a container and the env var not being passed through? Or is it a JS action?

**Comment by kzantow** [comment]
This `sbom-action` is a JS action.

**Comment by jdagostino9188** [comment]
We are hitting this same issue in our env.  Action not working w dind actions runner deployment.

**Comment by willmurphyscode** [comment]
Thanks for the comment @jdagostino9188 and @apr-1985! I wonder, can this issue be reproduced just by running syft in docker-in-docker without involving GitHub actions? That would make it much easier to work on. I'll try to reproduce it that way when I get a chance, but if anyone else could try to reproduce the issue just by running syft with docker in docker, or any way to reproduce it locally in general, that would be a huge help.

**Comment by apr-1985** [comment]
I have circled back round to this again. 
Using the latest Action release it is all working on my setup now, so whatever the issue was seems to have been resolved organically. 

This can probably be closed.

**Comment by kzantow** [comment]
Thanks for following up, @apr-1985 ! Please let us know if the problem resurfaces!
