### ISSUE TITLE
The "upload-artifact" functionality is not compatible with actions/download-artifact@v4

### ISSUE THREAD

**Issue by ViacheslavKudinov** [anchore/sbom-action#434]
Hello.
Due to the usage of `@actions/artifact@v2` under the hood of `actions/download-artifact@v4`,
the current version of `anchore/sbom-action` is not compatible with `actions/download-artifact@v4`.

It will be great to migrate to  [`@actions/artifact@v2` package](https://github.com/actions/toolkit/tree/main/packages/artifact#v2---whats-new)

**Comment by ViacheslavKudinov** [comment]
Hi @kzantow 
could you prioritize  one as it is blocker to use actions/download-artifact@v4 and main concern due to https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/ ?

**Comment by ViacheslavKudinov** [comment]
Moreover https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

**Comment by martincostello** [comment]
Just spotted this warning when testing out the action:

![image](https://github.com/anchore/sbom-action/assets/1439341/286d16d8-4726-48b1-88c0-d1858a1332e8)
