### ISSUE TITLE
 Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by mstoykov** [anchore/sbom-action#439]
Similar to https://github.com/anchore/sbom-action/issues/362 but now for node 16 

see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by ViacheslavKudinov** [comment]
Seems was fixed in https://github.com/anchore/sbom-action/pull/440 ?

**Comment by mstoykov** [comment]
Yeah, thanks @ViacheslavKudinov 

This was fixed with #440

**Comment by ViacheslavKudinov** [comment]
Actually nit for child Actions https://github.com/anchore/sbom-action/pull/448
