### ISSUE TITLE
Error "accepts at most 1 arg(s), received 2" is there in v0

### ISSUE THREAD

**Issue by LinLiKinto** [anchore/sbom-action#447]
It worked well till 5th March. But on 6th March, job failed.
I never changed my source code during these 2 days.
I think it was because of this PR:https://github.com/anchore/sbom-action/pull/446
New version is released, v0(I was using) is also updated after this PR.
I tried the old version of v0.15.8. It worked.

<img width="873" alt="image" src="https://github.com/anchore/sbom-action/assets/97220352/e9b275a6-acd9-4ae7-b62b-b670aef787bc">

**Comment by kzantow** [comment]
Thanks @harmw -- it looks like @LinLiKinto, you're using an older version of Syft and need to update to a version that uses the `scan` command, rather than `packages`. Just removing any pinned version should fix the problem. Are you able to give that a try?

**Comment by LinLiKinto** [comment]
@kzantow Thank you for your advice. But we are using https://github.com/xeol-io/xeol/pull/294  after anchore/sbom-action. They are not updated for new version of syft. If we update the version of syft, we will encounter error in that GitHub Action. 
But I got the point now. I will wait for their update. Before that, I will fix the version to v0.15.8. 
Thank you very much.

**Comment by popey** [comment]
Looks like the upstream issue on xeol is closed, so I presume this is no longer an sbom-action issue?
I'll close this, but feel free to open a new issue if required 🙏
