### ISSUE TITLE
Action has stopped working, fails to download syft

### ISSUE THREAD

**Issue by martincostello** [anchore/sbom-action#472]
[Since some time yesterday morning](https://github.com/martincostello/browserstack-automate/actions/workflows/build.yml?query=event%3Apush+branch%3Amain), the action has started failing to download syft in one of my repositories: [logs](https://github.com/martincostello/browserstack-automate/actions/runs/9395375698/job/25897099240#step:7:277)

```console
------------------------------ Running SBOM Action -----------------------------
::group::Got github context:
Got github context:
##[debug]isExplicit: 1.4.1
##[debug]explicit? true
##[debug]checking cache: C:\hostedtoolcache\windows\syft.exe\1.4.1\x64
##[debug]not found
##[debug]Installing syft v1.4.1
##[debug]Downloading https://raw.githubusercontent.com/anchore/syft/main/install.sh
##[debug]Destination D:\a\_temp\8121acb8-e422-4995-8af8-e1c646b74cd8
##[debug]download complete
"C:\Program Files\Git\bin\sh.exe" D:\a\_temp\8121acb8-e422-4995-8af8-e1c646b74cd8 -d -b D:\a\_temp\8121acb8-e422-4995-8af8-e1c646b74cd8_syft v1.4.1
[debug] checking github for release tag='v1.4.1' 
[debug] http_download(url=https://github.com/anchore/syft/releases/v1.4.1) 
Error:  received HTTP status=000 for url='https://github.com/anchore/syft/releases/v1.4.1' 
Error:  unable to find tag='' 
Error:  do not specify a version or select a valid version from https://github.com/anchore/syft/releases 
Error: The process 'C:\Program Files\Git\bin\sh.exe' failed with exit code 1
##[debug]Node Action run completed with exit code 1
```

I've also tried explicitly updating to a newer version of syft, and that [also fails](https://github.com/martincostello/browserstack-automate/actions/runs/9402696576/job/25898081989?pr=680#step:7:629):

```console
------------------------------ Running SBOM Action -----------------------------
::group::Got github context:
Got github context:
##[debug]isExplicit: 1.5.0
##[debug]explicit? true
##[debug]checking cache: C:\hostedtoolcache\windows\syft.exe\1.5.0\x64
##[debug]not found
##[debug]Installing syft v1.5.0
##[debug]Downloading https://raw.githubusercontent.com/anchore/syft/main/install.sh
##[debug]Destination D:\a\_temp\a676dc61-1046-48b4-8ed6-b02c33920005
##[debug]download complete
"C:\Program Files\Git\bin\sh.exe" D:\a\_temp\a676dc61-1046-48b4-8ed6-b02c33920005 -d -b D:\a\_temp\a676dc61-1046-48b4-8ed6-b02c33920005_syft v1.5.0
[debug] checking github for release tag='v1.5.0' 
[debug] http_download(url=https://github.com/anchore/syft/releases/v1.5.0) 
Error:  received HTTP status=000 for url='https://github.com/anchore/syft/releases/v1.5.0' 
Error:  unable to find tag='' 
Error:  do not specify a version or select a valid version from https://github.com/anchore/syft/releases 
Error: The process 'C:\Program Files\Git\bin\sh.exe' failed with exit code 1
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Generate SBOM
```

I'm using the action pinned to anchore/sbom-action@e8d2a6937ecead383dfe75190d104edd1f9c5751 for the v0.16 tag.

**Comment by tgerla** [comment]
Hi @martincostello, thanks for the report. I did a little bit of basic testing on my macOS machine and it looks like GitHub is working OK right now. We have seen rare API outages from GitHub which cause problems like this but I don't think that's the case here. Looking at your builds it looks like the Windows version is the only one that's failing. Am I reading that right? Have there been any other changes to your environment lately, particularly in the Windows build?

**Comment by martincostello** [comment]
It's true that it's the Windows version, but I only generate the SBOM on Windows as that's the platform I ship my artifacts from of the three. I've not explicitly changed anything myself in the environment, I just use the `windows-latest` label and get whatever GitHub serves up.

**Comment by tgerla** [comment]
OK. Can you do me a favor and manually trigger one of these jobs and make sure it repeats the failure? I am not getting any useful info from the logs, it looks like a generic networking error fetching the release archive. I looked at the GitHub runner commits and it looks like some Docker components updated on the standard images yesterday. (https://github.com/actions/runner-images/commit/7992e7f1badb63f581dbf973a251abc76f0f963a)

**Comment by tgerla** [comment]
Thank you. That is odd. The `received HTTP status=000` message is shown "for any 200 or 206 responses with a client abort: the object was served correctly from the origin or edge, but the end-user terminated the connection/transaction before it completed."

We don't think we've made any chances on our side that would cause this. I am seeing some other folks reporting various problems with the new windows-latest image: https://github.com/actions/runner-images/issues/10004 -- different symptoms, though. Unfortunately I don't believe there is any way to request a previous version of the runner image to eliminate that as a variable, unless I am missing something. I will let you know if we run across anything else helpful in the meantime.

**Comment by kzantow** [comment]
I can confirm this looks to be failing on windows runners: https://github.com/kzantow-anchore/sbom-action-test/actions/runs/9405721903/job/25907548486 

Seeing as nothing has changed in `sbom-action` or `syft`, I suspect @tgerla is right that something has changed on the most recent windows runner. It's unclear exactly what we could do to solve this.

**Comment by martincostello** [comment]
Finding this in more or more repos as dependabot updates are coming in - for now I'm just going to have to turn it off as otherwise it's blocking my releases 😢

**Comment by popey** [comment]
Thanks for the issue report. This is looking like an upstream runner-on-windows curl issue which appears to now be fixed? 

Do feel free to file a new issue if the sbom-action continues to fail. Thanks again 🙏

**Comment by martincostello** [comment]
The fix doesn't appear to have rolled out to the Windows runner. The action still fails for me.

**Comment by kzantow** [comment]
I'm not sure why they closed https://github.com/actions/runner-images/issues/10009, it hasn't been fixed although a fix looks like it's been made in curl it hasn't been incorporated back into the runners. 😕

**Comment by willmurphyscode** [comment]
@martincostello https://github.com/anchore/sbom-action/releases/tag/v0.16.1 should be fixed now. Please let us know if you have any issues. Thanks!

**Comment by max06** [comment]
Good morning. Just wanted to let you know that this is currently happening repeatedly to us, on standard ubuntu runners. Fetching tags returns 504s, probably something github api related.

**Comment by martincostello** [comment]
This is probably [this GitHub incident](https://www.githubstatus.com/incidents/m7n7sm0sr1pz).

**Comment by max06** [comment]
Sorry, can't agree with that. Our issue appeared one or two weeks ago already. Actions are fine (for us), it's just the download of syft. 

Would the action still try to fetch the latest tags/download the latest release if syft was already present on the runner? I'd create an extra download step then with a loop/delay to work around this issue...

**Comment by martincostello** [comment]
Well I only mentioned it because I haven't had this issue, then about the time of the incident a tonne of my CI jobs started failing trying to download various artifacts from GitHub, then just after I posted that comment I reran all the failing jobs and they all succeeded.

I suggest you create a new issue.
